# Generated by Django 4.0.2 on 2022-07-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_message_from_client_message_is_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='user_name',
            new_name='client_name',
        ),
        migrations.AddField(
            model_name='dialog',
            name='avatar_num',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
