# Generated by Django 4.0.2 on 2022-07-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_name_dialog_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='client_name',
            new_name='user_name',
        ),
    ]
