# Generated by Django 4.0.2 on 2022-07-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_surname'),
        ('chat', '0004_rename_client_name_dialog_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='operator_name',
        ),
        migrations.AddField(
            model_name='dialog',
            name='operator',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
