# Generated by Django 4.0.2 on 2022-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsOperator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsdata',
            name='send_messages',
            field=models.IntegerField(null=True),
        ),
    ]
