# Generated by Django 4.0.2 on 2022-07-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsOperator', '0002_statisticsdata_send_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsdata',
            name='login',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
